name: Close Issues on Push

on:
  push:
    branches:
      - dev
permissions:
      contents: read
      issues: write
jobs:
  close-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Close issues from commit messages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取所有提交信息
          commits=$(git log --format=%B -n 10) # 获取最近 10 个提交的信息
          echo "$commits"
          echo ""
          # 查找并关闭与关键字匹配的 issue
          echo "$commits" | grep -oE '(close(s|d)?|fix(ed|es)?|resolve(s|d)?) #[0-9]+' | while read -r line; do
            echo "$line"
            issue_number=$(echo "$line" | grep -oE '[0-9]+')
            echo "Closing issue #$issue_number"
            curl -X PATCH \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d '{"state": "closed"}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number"
          done
